# Generated by Django 3.2.8 on 2021-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychics',
            name='all_numders',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='psychics',
            name='credibility',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
